# QPM : Assignment 8

By Valentin PICAVET

# Data

In [1]:
import numpy as np
import pandas as pd 

In [2]:
data = pd.read_excel("QPM-FactorsData.xlsx")
data

Dates  Market     SMB     HML     RMW     CMA     UMD       ROE  \
0    196702  0.0078  0.0334 -0.0217  0.0194 -0.0094  0.0356  0.035317   
1    196703  0.0399  0.0163  0.0031  0.0090 -0.0151  0.0142  0.018876   
2    196704  0.0389  0.0062 -0.0264  0.0243 -0.0375  0.0064  0.010983   
3    196705 -0.0433  0.0198  0.0080 -0.0175  0.0161  0.0067  0.005234   
4    196706  0.0241  0.0596  0.0096 -0.0064 -0.0239  0.0603  0.002945   
..      ...     ...     ...     ...     ...     ...     ...       ...   
642  202008  0.0763 -0.0094 -0.0294  0.0427 -0.0144  0.0051 -0.008682   
643  202009 -0.0363  0.0007 -0.0251 -0.0115 -0.0177  0.0305  0.012255   
644  202010 -0.0210  0.0476  0.0403 -0.0060 -0.0053 -0.0303 -0.024671   
645  202011  0.1247  0.0675  0.0211 -0.0278  0.0105 -0.1225 -0.144600   
646  202012  0.0463  0.0467 -0.0136 -0.0215  0.0000 -0.0242 -0.035415   

           IA     BAB  
0   -0.002064  0.0262  
1   -0.016933  0.0081  
2   -0.029519  0.0171  
3    0.024686  0.0201  
4   -0.021700 -0.0163  
..        ...     ...  
642 -0.028534 -0.0399  
643 -0.021992  0.0129  
644 -0.007387 -0.0201  
645  0.030672 -0.0509  
646 -0.027001  0.0534  

[647 rows x 10 columns]

In [3]:
data['Dates'] = pd.to_datetime(data['Dates'], format='%Y%m')
data = data.set_index('Dates')
data.index = data.index.strftime('%Y-%m')
data

Market     SMB     HML     RMW     CMA     UMD       ROE        IA  \
Dates                                                                         
1967-02  0.0078  0.0334 -0.0217  0.0194 -0.0094  0.0356  0.035317 -0.002064   
1967-03  0.0399  0.0163  0.0031  0.0090 -0.0151  0.0142  0.018876 -0.016933   
1967-04  0.0389  0.0062 -0.0264  0.0243 -0.0375  0.0064  0.010983 -0.029519   
1967-05 -0.0433  0.0198  0.0080 -0.0175  0.0161  0.0067  0.005234  0.024686   
1967-06  0.0241  0.0596  0.0096 -0.0064 -0.0239  0.0603  0.002945 -0.021700   
...         ...     ...     ...     ...     ...     ...       ...       ...   
2020-08  0.0763 -0.0094 -0.0294  0.0427 -0.0144  0.0051 -0.008682 -0.028534   
2020-09 -0.0363  0.0007 -0.0251 -0.0115 -0.0177  0.0305  0.012255 -0.021992   
2020-10 -0.0210  0.0476  0.0403 -0.0060 -0.0053 -0.0303 -0.024671 -0.007387   
2020-11  0.1247  0.0675  0.0211 -0.0278  0.0105 -0.1225 -0.144600  0.030672   
2020-12  0.0463  0.0467 -0.0136 -0.0215  0.0000 -0.0242 -0.035415 -0.027001   

            BAB  
Dates            
1967-02  0.0262  
1967-03  0.0081  
1967-04  0.0171  
1967-05  0.0201  
1967-06 -0.0163  
...         ...  
2020-08 -0.0399  
2020-09  0.0129  
2020-10 -0.0201  
2020-11 -0.0509  
2020-12  0.0534  

[647 rows x 9 columns]

In [4]:
data_comparison=data.loc["1977-01":"2020-12"]
data_comparison

Market     SMB     HML     RMW     CMA     UMD       ROE        IA  \
Dates                                                                         
1977-01 -0.0405  0.0478  0.0426 -0.0053  0.0193  0.0398 -0.021494  0.009953   
1977-02 -0.0194  0.0108  0.0050 -0.0013 -0.0019  0.0035  0.012510  0.001210   
1977-03 -0.0137  0.0099  0.0102 -0.0032 -0.0009  0.0049  0.002845 -0.001567   
1977-04  0.0015 -0.0012  0.0345 -0.0203  0.0116  0.0422  0.003708  0.012277   
1977-05 -0.0145  0.0118  0.0084  0.0033  0.0011  0.0201  0.017462  0.002061   
...         ...     ...     ...     ...     ...     ...       ...       ...   
2020-08  0.0763 -0.0094 -0.0294  0.0427 -0.0144  0.0051 -0.008682 -0.028534   
2020-09 -0.0363  0.0007 -0.0251 -0.0115 -0.0177  0.0305  0.012255 -0.021992   
2020-10 -0.0210  0.0476  0.0403 -0.0060 -0.0053 -0.0303 -0.024671 -0.007387   
2020-11  0.1247  0.0675  0.0211 -0.0278  0.0105 -0.1225 -0.144600  0.030672   
2020-12  0.0463  0.0467 -0.0136 -0.0215  0.0000 -0.0242 -0.035415 -0.027001   

            BAB  
Dates            
1977-01  0.0407  
1977-02  0.0249  
1977-03  0.0123  
1977-04  0.0106  
1977-05  0.0104  
...         ...  
2020-08 -0.0399  
2020-09  0.0129  
2020-10 -0.0201  
2020-11 -0.0509  
2020-12  0.0534  

[528 rows x 9 columns]

In [5]:
data_vol=data.rolling(window=12).std().dropna().loc["1977-01":"2020-12"]*np.sqrt(12)
data_vol

Market       SMB       HML       RMW       CMA       UMD       ROE  \
Dates                                                                           
1977-01  0.096141  0.095635  0.070550  0.043175  0.054996  0.051909  0.055079   
1977-02  0.098762  0.069624  0.050597  0.035551  0.041223  0.051912  0.040961   
1977-03  0.096714  0.067298  0.049731  0.035510  0.039958  0.051805  0.032871   
1977-04  0.095668  0.067407  0.054427  0.039682  0.039236  0.063640  0.032893   
1977-05  0.095838  0.064201  0.047329  0.026960  0.034921  0.060881  0.036864   
...           ...       ...       ...       ...       ...       ...       ...   
2020-08  0.243311  0.109510  0.168519  0.062757  0.068316  0.164532  0.078498   
2020-09  0.249708  0.109812  0.133890  0.062007  0.053463  0.145562  0.077876   
2020-10  0.252225  0.122536  0.153419  0.062340  0.053575  0.151553  0.083122   
2020-11  0.275729  0.141381  0.161509  0.066969  0.056527  0.199426  0.168971   
2020-12  0.276982  0.148382  0.154868  0.070057  0.052954  0.199810  0.171013   

               IA       BAB  
Dates                        
1977-01  0.044880  0.052740  
1977-02  0.040159  0.053562  
1977-03  0.036449  0.049609  
1977-04  0.037418  0.048755  
1977-05  0.035325  0.047127  
...           ...       ...  
2020-08  0.072798  0.162154  
2020-09  0.062769  0.162546  
2020-10  0.062647  0.163692  
2020-11  0.074835  0.169118  
2020-12  0.071853  0.178593  

[528 rows x 9 columns]

In [6]:
data_volatility_managed=data_comparison.copy()
data_volatility_managed

Market     SMB     HML     RMW     CMA     UMD       ROE        IA  \
Dates                                                                         
1977-01 -0.0405  0.0478  0.0426 -0.0053  0.0193  0.0398 -0.021494  0.009953   
1977-02 -0.0194  0.0108  0.0050 -0.0013 -0.0019  0.0035  0.012510  0.001210   
1977-03 -0.0137  0.0099  0.0102 -0.0032 -0.0009  0.0049  0.002845 -0.001567   
1977-04  0.0015 -0.0012  0.0345 -0.0203  0.0116  0.0422  0.003708  0.012277   
1977-05 -0.0145  0.0118  0.0084  0.0033  0.0011  0.0201  0.017462  0.002061   
...         ...     ...     ...     ...     ...     ...       ...       ...   
2020-08  0.0763 -0.0094 -0.0294  0.0427 -0.0144  0.0051 -0.008682 -0.028534   
2020-09 -0.0363  0.0007 -0.0251 -0.0115 -0.0177  0.0305  0.012255 -0.021992   
2020-10 -0.0210  0.0476  0.0403 -0.0060 -0.0053 -0.0303 -0.024671 -0.007387   
2020-11  0.1247  0.0675  0.0211 -0.0278  0.0105 -0.1225 -0.144600  0.030672   
2020-12  0.0463  0.0467 -0.0136 -0.0215  0.0000 -0.0242 -0.035415 -0.027001   

            BAB  
Dates            
1977-01  0.0407  
1977-02  0.0249  
1977-03  0.0123  
1977-04  0.0106  
1977-05  0.0104  
...         ...  
2020-08 -0.0399  
2020-09  0.0129  
2020-10 -0.0201  
2020-11 -0.0509  
2020-12  0.0534  

[528 rows x 9 columns]

In [7]:
c=1
for factors in data_volatility_managed.columns:
    for dates in data_volatility_managed.index:
        data_volatility_managed[factors].loc[dates]=(c/data_vol[factors].loc[dates]**2)*data_comparison[factors].loc[dates]
data_volatility_managed

Market       SMB        HML        RMW       CMA        UMD  \
Dates                                                                    
1977-01 -4.381637  5.226252   8.558798  -2.843210  6.381195  14.770446   
1977-02 -1.988952  2.227939   1.953083  -1.028611 -1.118058   1.298759   
1977-03 -1.464664  2.185899   4.124321  -2.537815 -0.563695   1.825764   
1977-04  0.163891 -0.264102  11.646352 -12.891776  7.534958  10.419594   
1977-05 -1.578688  2.862870   3.749874   4.540338  0.902051   5.422835   
...           ...       ...        ...        ...       ...        ...   
2020-08  1.288848 -0.783831  -1.035258  10.841839 -3.085405   0.188395   
2020-09 -0.582159  0.058050  -1.400164  -2.991017 -6.192417   1.439466   
2020-10 -0.330099  3.170139   1.712171  -1.543874 -1.846524  -1.319216   
2020-11  1.640222  3.376937   0.808893  -6.198575  3.286072  -3.080151   
2020-12  0.603499  2.121063  -0.567045  -4.380616  0.000000  -0.606150   

               ROE        IA        BAB  
Dates                                    
1977-01  -7.085093  4.941452  14.632211  
1977-02   7.456063  0.750287   8.679359  
1977-03   2.633024 -1.179521   4.997778  
1977-04   3.427130  8.768401   4.459309  
1977-05  12.849244  1.651626   4.682713  
...            ...       ...        ...  
2020-08  -1.408967 -5.384236  -1.517457  
2020-09   2.020711 -5.581877   0.488245  
2020-10  -3.570669 -1.882185  -0.750137  
2020-11  -5.064596  5.476896  -1.779654  
2020-12  -1.210953 -5.229928   1.674210  

[528 rows x 9 columns]

# Question 1

Please use mean-variance optimization to combine :
- The original (without timing) factor, $f_{t+1}$;
- The volatility-managed version of this factor, $f^{\sigma}_{t+1}$

In [8]:
from scipy.optimize import minimize

def mean_variance_objective(weights, returns):
    portfolio_return = weights.T @ returns.mean()
    portfolio_volatility = np.sqrt(np.dot(weights.T, np.dot(returns.cov(), weights)))
    return -portfolio_return / portfolio_volatility

def maximize_SR(returns):
    num_assets = returns.shape[1]

    # Set initial weights
    initial_weights = np.ones(num_assets) / num_assets
    # Minimize the negative SR  to maximize the SR 
    result = minimize(mean_variance_objective, initial_weights, args=(returns,), method='SLSQP')

    return result.x

In [9]:
mkt=pd.concat([data_volatility_managed['Market'],data_comparison['Market']],axis=1)
optimal_mkt_weight=maximize_SR(mkt)
optimal_mkt_weight

array([0.5, 0.5])

In [10]:
smb=pd.concat([data_volatility_managed['SMB'],data_comparison['SMB']],axis=1)
optimal_smb_weight=maximize_SR(smb)
optimal_smb_weight

array([0.5, 0.5])

In [11]:
rmw=pd.concat([data_volatility_managed['RMW'],data_comparison['RMW']],axis=1)
optimal_rmw_weight=maximize_SR(rmw)
optimal_rmw_weight

array([0.5, 0.5])

In [12]:
hml=pd.concat([data_volatility_managed['HML'],data_comparison['HML']],axis=1)
optimal_hml_weight=maximize_SR(hml)
optimal_hml_weight

array([0.5, 0.5])

In [13]:
cma=pd.concat([data_volatility_managed['CMA'],data_comparison['CMA']],axis=1)
optimal_cma_weight=maximize_SR(cma)
optimal_cma_weight

array([0.5, 0.5])

In [14]:
umd=pd.concat([data_volatility_managed['UMD'],data_comparison['UMD']],axis=1)
optimal_umd_weight=maximize_SR(umd)
optimal_umd_weight

array([ 149.02895239, -152.2291495 ])

In [15]:
roe=pd.concat([data_volatility_managed['ROE'],data_comparison['ROE']],axis=1)
optimal_roe_weight=maximize_SR(roe)
optimal_roe_weight

array([0.5, 0.5])

In [16]:
ia=pd.concat([data_volatility_managed['IA'],data_comparison['IA']],axis=1)
optimal_ia_weight=maximize_SR(ia)
optimal_ia_weight

array([0.5, 0.5])

In [17]:
bab=pd.concat([data_volatility_managed['BAB'],data_comparison['BAB']],axis=1)
optimal_bab_weight=maximize_SR(bab)
optimal_bab_weight

array([0.5, 0.5])

There is a problem with my code because when I use it, it always return initial weights. It seems like my code is not doing anything but I don't know why. We spent a lot of time trying to fix the issue but we didn't succeed.

# Question 2

Compare the Sharpe ratios of :
- the portfolio with just the original factor and
- the portfolio that includes the volatility-timed factor.

In [18]:
expected_returns = [data_comparison[factor].mean() for factor in data_comparison.columns]
expected_returns

[0.006779734848484849,
 0.0018854166666666663,
 0.0015206439393939395,
 0.003310037878787879,
 0.002269128787878788,
 0.006098106060606061,
 0.005333676136363636,
 0.002749931818181818,
 0.00909469696969697]

In [19]:
st_dev = [data_comparison[factor].std() for factor in data_comparison.columns]
st_dev

[0.04486282725997977,
 0.03001609238563706,
 0.02949552003358049,
 0.02277460538566905,
 0.019439093164871836,
 0.04408176717810558,
 0.025823914819238934,
 0.018642354405263125,
 0.03557499028634923]

In [20]:
sharpe_ratio_original = pd.DataFrame(index=data_comparison.columns)
sharpe_ratio_original['Original SR']=[(er / sd)*np.sqrt(12) for er, sd in zip(expected_returns, st_dev)]
sharpe_ratio_original

Original SR
Market     0.523500
SMB        0.217592
HML        0.178592
RMW        0.503469
CMA        0.404365
UMD        0.479211
ROE        0.715476
IA         0.510989
BAB        0.885593

In [21]:
data_mkt=pd.DataFrame(index=mkt.index, columns=['MKT Returns'])
for i in range (len(mkt)):
    data_mkt.iloc[i]=(optimal_mkt_weight*mkt.iloc[i]).sum()

data_mkt

MKT Returns
Dates              
1977-01   -2.211069
1977-02   -1.004176
1977-03   -0.739182
1977-04    0.082696
1977-05   -0.796594
...             ...
2020-08    0.682574
2020-09   -0.309229
2020-10    -0.17555
2020-11    0.882461
2020-12      0.3249

[528 rows x 1 columns]

In [22]:
data_smb=pd.DataFrame(index=smb.index, columns=['SMB Returns'])
for i in range (len(smb)):
    data_smb.iloc[i]=(optimal_smb_weight*smb.iloc[i]).sum()

data_smb

SMB Returns
Dates              
1977-01    2.637026
1977-02    1.119369
1977-03      1.0979
1977-04   -0.132651
1977-05    1.437335
...             ...
2020-08   -0.396615
2020-09    0.029375
2020-10    1.608869
2020-11    1.722219
2020-12    1.083882

[528 rows x 1 columns]

In [23]:
data_rmw=pd.DataFrame(index=rmw.index, columns=['RMW Returns'])
for i in range (len(rmw)):
    data_rmw.iloc[i]=(optimal_rmw_weight*rmw.iloc[i]).sum()

data_rmw

RMW Returns
Dates              
1977-01   -1.424255
1977-02   -0.514956
1977-03   -1.270507
1977-04   -6.456038
1977-05    2.271819
...             ...
2020-08    5.442269
2020-09   -1.501258
2020-10   -0.774937
2020-11   -3.113187
2020-12   -2.201058

[528 rows x 1 columns]

In [24]:
data_hml=pd.DataFrame(index=hml.index, columns=['HML Returns'])
for i in range (len(hml)):
    data_hml.iloc[i]=(optimal_hml_weight*hml.iloc[i]).sum()

data_hml

HML Returns
Dates              
1977-01    4.300699
1977-02    0.979042
1977-03     2.06726
1977-04    5.840426
1977-05    1.879137
...             ...
2020-08   -0.532329
2020-09   -0.712632
2020-10    0.876236
2020-11    0.414997
2020-12   -0.290323

[528 rows x 1 columns]

In [25]:
data_cma=pd.DataFrame(index=cma.index, columns=['CMA Returns'])
for i in range (len(cma)):
    data_cma.iloc[i]=(optimal_cma_weight*cma.iloc[i]).sum()

data_cma

CMA Returns
Dates              
1977-01    3.200248
1977-02   -0.559979
1977-03   -0.282298
1977-04    3.773279
1977-05    0.451576
...             ...
2020-08   -1.549902
2020-09   -3.105059
2020-10   -0.925912
2020-11    1.648286
2020-12         0.0

[528 rows x 1 columns]

In [26]:
data_umd=pd.DataFrame(index=umd.index, columns=['UMD Returns'])
for i in range (len(umd)):
    data_umd.iloc[i]=(optimal_umd_weight*umd.iloc[i]).sum()

data_umd

UMD Returns
Dates               
1977-01  2195.165336
1977-02    193.01991
1977-03   271.345845
1977-04  1546.397115
1977-05   805.099645
...              ...
2020-08    27.299912
2020-09   209.879151
2020-10  -191.988881
2020-11  -440.383566
2020-12   -86.649893

[528 rows x 1 columns]

In [27]:
data_roe=pd.DataFrame(index=roe.index, columns=['ROE Returns'])
for i in range (len(roe)):
    data_roe.iloc[i]=(optimal_roe_weight*roe.iloc[i]).sum()

data_roe

ROE Returns
Dates              
1977-01   -3.553293
1977-02    3.734286
1977-03    1.317934
1977-04    1.715419
1977-05    6.433353
...             ...
2020-08   -0.708825
2020-09    1.016483
2020-10    -1.79767
2020-11   -2.604598
2020-12   -0.623184

[528 rows x 1 columns]

In [28]:
data_ia=pd.DataFrame(index=ia.index, columns=['IA Returns'])
for i in range (len(ia)):
    data_ia.iloc[i]=(optimal_ia_weight*ia.iloc[i]).sum()

data_ia

IA Returns
Dates             
1977-01   2.475702
1977-02   0.375748
1977-03  -0.590544
1977-04   4.390339
1977-05   0.826844
...            ...
2020-08  -2.706385
2020-09  -2.801935
2020-10  -0.944786
2020-11   2.753784
2020-12  -2.628464

[528 rows x 1 columns]

In [29]:
data_bab=pd.DataFrame(index=bab.index, columns=['BAB Returns'])
for i in range (len(bab)):
    data_bab.iloc[i]=(optimal_bab_weight*bab.iloc[i]).sum()

data_bab

BAB Returns
Dates              
1977-01    7.336455
1977-02     4.35213
1977-03    2.505039
1977-04    2.234954
1977-05    2.346557
...             ...
2020-08   -0.778678
2020-09    0.250572
2020-10   -0.385118
2020-11   -0.915277
2020-12    0.863805

[528 rows x 1 columns]

In [30]:
data_wvol=pd.concat([data_mkt,data_smb,data_rmw,data_hml,data_cma,data_umd,data_roe,data_ia,data_bab],axis=1)
data_wvol 

MKT Returns SMB Returns RMW Returns HML Returns CMA Returns  \
Dates                                                                 
1977-01   -2.211069    2.637026   -1.424255    4.300699    3.200248   
1977-02   -1.004176    1.119369   -0.514956    0.979042   -0.559979   
1977-03   -0.739182      1.0979   -1.270507     2.06726   -0.282298   
1977-04    0.082696   -0.132651   -6.456038    5.840426    3.773279   
1977-05   -0.796594    1.437335    2.271819    1.879137    0.451576   
...             ...         ...         ...         ...         ...   
2020-08    0.682574   -0.396615    5.442269   -0.532329   -1.549902   
2020-09   -0.309229    0.029375   -1.501258   -0.712632   -3.105059   
2020-10    -0.17555    1.608869   -0.774937    0.876236   -0.925912   
2020-11    0.882461    1.722219   -3.113187    0.414997    1.648286   
2020-12      0.3249    1.083882   -2.201058   -0.290323         0.0   

         UMD Returns ROE Returns IA Returns BAB Returns  
Dates                                                    
1977-01  2195.165336   -3.553293   2.475702    7.336455  
1977-02    193.01991    3.734286   0.375748     4.35213  
1977-03   271.345845    1.317934  -0.590544    2.505039  
1977-04  1546.397115    1.715419   4.390339    2.234954  
1977-05   805.099645    6.433353   0.826844    2.346557  
...              ...         ...        ...         ...  
2020-08    27.299912   -0.708825  -2.706385   -0.778678  
2020-09   209.879151    1.016483  -2.801935    0.250572  
2020-10  -191.988881    -1.79767  -0.944786   -0.385118  
2020-11  -440.383566   -2.604598   2.753784   -0.915277  
2020-12   -86.649893   -0.623184  -2.628464    0.863805  

[528 rows x 9 columns]

In [31]:
expected_returns_vol = [data_wvol[factor].mean() for factor in data_wvol.columns]
expected_returns_vol

[0.32242533133288576,
 0.1306192375950935,
 0.6838092021547334,
 0.04650392463790797,
 0.23716595620094794,
 180.81927255497817,
 1.0891777827659914,
 0.49167741757868155,
 1.0727861889498302]

In [32]:
st_dev_vol = [data_wvol[factor].std() for factor in data_wvol.columns]
st_dev_vol

[1.4782440510617056,
 2.3013926736576793,
 3.368103236126205,
 2.243358750313567,
 3.0652696249424896,
 543.4870423727439,
 2.908862212553268,
 3.157815154471618,
 2.7237655453172382]

In [33]:
sharpe_ratio_factors_vol = pd.DataFrame(index=data_comparison.columns)
sharpe_ratio_factors_vol['Volatility Managed SR']=[(er / sd)*np.sqrt(12) for er, sd in zip(expected_returns_vol, st_dev_vol)]
sharpe_ratio_factors_vol

Volatility Managed SR
Market               0.755568
SMB                  0.196611
HML                  0.703299
RMW                  0.071809
CMA                  0.268024
UMD                  1.152514
ROE                  1.297078
IA                   0.539367
BAB                  1.364376

In [34]:
pd.concat([sharpe_ratio_original,sharpe_ratio_factors_vol],axis=1)

Original SR  Volatility Managed SR
Market     0.523500               0.755568
SMB        0.217592               0.196611
HML        0.178592               0.703299
RMW        0.503469               0.071809
CMA        0.404365               0.268024
UMD        0.479211               1.152514
ROE        0.715476               1.297078
IA         0.510989               0.539367
BAB        0.885593               1.364376

# Question 3

What do you conclude from your analysis above?

We can conclude that in most cases the portfolio that includes the volatility-timed factor has a higher Sharpe Ratio than the portfolio with just the original factor except for RMW and CMA factors.

However, the assessment relies on historical data confined to a specific timeframe. The efficacy of timing market volatility may fluctuate under diverse market conditions, and past performance does not necessarily predict future outcomes.

A heightened Sharpe ratio in the portfolio incorporating the volatility-timed factor implies potentially superior risk-adjusted performance compared to the original factor portfolio. Nevertheless, relying exclusively on Sharpe ratios has its constraints, as it overlooks factors like tail risk, shifts in market conditions, and behavioral tendencies. Investors should exercise caution, refraining from making decisions solely based on Sharpe ratios, and instead, adopt a comprehensive risk management strategy when deploying volatility-timed strategies in real-world investment scenarios.

# Question 4

Please list the limitations of your analysis. Could one implement this volatility-timing policy in practice?

There are several limitations which are:

- Out-of-sample Sensitivity: The Sharpe ratio beyond the analyzed period might experience a notable decrease.
- Transaction Costs: The effectiveness of arbitrage strategies is susceptible to the impact of transaction costs.
- Market Sentiment Dependency: Strategies of this nature may be responsive to the prevailing sentiment in the market.

To overcome these limitations, investors should turn their attention to the results derived from multifactor portfolios by DeMiguel, Martin-Utrera, and Uppal. These findings indicate substantial performance enhancements resulting from volatility timing, encompassing aspects such as out-of-sample performance, net transaction costs, and applicability in both low- and high-sentiment periods.

While the analysis suggests an augmented Sharpe ratio for portfolios incorporating the volatility-timed factor, it is crucial to recognize various limitations. Historical performance might not reliably predict future outcomes. Implementing volatility-timing strategies in practical scenarios introduces challenges such as transaction costs, liquidity constraints, and the potential for model overfitting. The observed outperformance may hinge on specific market conditions or time frames. Furthermore, shifts in market dynamics can alter the effectiveness of volatility-timing approaches. A thoughtful evaluation of these limitations is essential before integrating such strategies into real-world investment practices.